// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../server/worker'

export type PageName = 'Admin/Index' | 'Admin/Reviews' | 'Admin/Tags' | 'Admin/Users' | 'Auth/Invite' | 'Auth/Login' | 'Home' | 'Public/Release' | 'Public/Review' | 'Reviews/Dashboard' | 'Reviews/Edit' | 'Reviews/New'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Admin/Index': unknown
    'Admin/Reviews': unknown
    'Admin/Tags': unknown
    'Admin/Users': unknown
    'Auth/Invite': unknown
    'Auth/Login': unknown
    'Home': unknown
    'Public/Release': unknown
    'Public/Review': unknown
    'Reviews/Dashboard': unknown
    'Reviews/Edit': unknown
    'Reviews/New': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
